# Generated by Django 4.2.27 on 2025-12-16 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("population", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="PointOfInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("supermarket", "Auchan"),
                            ("station", "Station-service"),
                            ("bus_station", "Gare routière"),
                        ],
                        max_length=20,
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("estimated_traffic", models.IntegerField(default=0)),
                ("recommended_capacity", models.IntegerField(default=0)),
                ("needs_locker", models.BooleanField(default=True)),
                (
                    "commune",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lockers.commune",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lockers.region"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Locker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("total", models.IntegerField()),
                ("installation_cost", models.IntegerField()),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "Haute"), (2, "Moyenne"), (3, "Basse")]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("planned", "Planifié"), ("active", "Actif")],
                        max_length=10,
                    ),
                ),
                (
                    "commune",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lockers.commune",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lockers.region"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Departement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lockers.region"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="commune",
            name="departement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lockers.departement"
            ),
        ),
    ]
