# Generated by Django 4.2.27 on 2025-12-16 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lockers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="departement",
            name="region",
        ),
        migrations.RenameField(
            model_name="pointofinterest",
            old_name="brand",
            new_name="commune_name",
        ),
        migrations.RemoveField(
            model_name="locker",
            name="commune",
        ),
        migrations.RemoveField(
            model_name="pointofinterest",
            name="commune",
        ),
        migrations.RemoveField(
            model_name="region",
            name="population",
        ),
        migrations.AddField(
            model_name="locker",
            name="commune_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="locker",
            name="poi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lockers",
                to="lockers.pointofinterest",
            ),
        ),
        migrations.AddField(
            model_name="pointofinterest",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="locker",
            name="installation_cost",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="locker",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="pointofinterest",
            name="category",
            field=models.CharField(
                choices=[
                    ("supermarket", "Supermarché"),
                    ("station", "Station-service"),
                    ("bus_station", "Gare routière"),
                    ("airport", "Aéroport"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pointofinterest",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name="Commune",
        ),
        migrations.DeleteModel(
            name="Departement",
        ),
    ]
