# Generated by Django 4.2.27 on 2025-12-18 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lockers", "0002_remove_departement_region_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("SUPERMARKET", "Supermarché"),
                            ("STATION", "Station-service"),
                            ("GARE", "Gare routière"),
                        ],
                        max_length=20,
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("commune", models.CharField(blank=True, max_length=100, null=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrateur"),
                            ("OPERATOR", "Opérateur"),
                            ("VIEWER", "Consultation"),
                        ],
                        default="VIEWER",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="locker",
            name="commune_name",
        ),
        migrations.RemoveField(
            model_name="locker",
            name="installation_cost",
        ),
        migrations.RemoveField(
            model_name="locker",
            name="lat",
        ),
        migrations.RemoveField(
            model_name="locker",
            name="lng",
        ),
        migrations.RemoveField(
            model_name="locker",
            name="name",
        ),
        migrations.RemoveField(
            model_name="locker",
            name="poi",
        ),
        migrations.RemoveField(
            model_name="locker",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="locker",
            name="region",
        ),
        migrations.RemoveField(
            model_name="locker",
            name="status",
        ),
        migrations.RemoveField(
            model_name="locker",
            name="total",
        ),
        migrations.AddField(
            model_name="locker",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="locker",
            name="installed_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="locker",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name="PointOfInterest",
        ),
        migrations.DeleteModel(
            name="Region",
        ),
        migrations.AddField(
            model_name="locker",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lockers",
                to="lockers.location",
            ),
        ),
    ]
